CREATE TABLE "Workshop" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text,
  "date" date NOT NULL,
  "location" varchar,
  "mentor_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Activity" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workshop_id" int NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "start_time"  timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Mentor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "Learner" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TYPE workshop_status AS ENUM ('pending', 'confirmed', 'cancelled');

CREATE TABLE "Enrollment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "learner_id" int NOT NULL,
  "workshop_id" int NOT NULL,
  status workshop_status DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TYPE user_type AS ENUM ('mentor', 'learner');

CREATE TABLE "Notification" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
   user_ty  user_type NOT NULL,
  "message" text NOT NULL,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "GoogleIntegration" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
   user_ty  user_type NOT NULL,
  "calendar_id" varchar NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "Workshop" ADD FOREIGN KEY ("mentor_id") REFERENCES "Mentor" ("id");

ALTER TABLE "Activity" ADD FOREIGN KEY ("workshop_id") REFERENCES "Workshop" ("id");

ALTER TABLE "Enrollment" ADD FOREIGN KEY ("learner_id") REFERENCES "Learner" ("id");

ALTER TABLE "Enrollment" ADD FOREIGN KEY ("workshop_id") REFERENCES "Workshop" ("id");
